go get github.com/gorilla/mux
go get github.com/jmcvetta/napping
go get github.com/pebbe/zmq4
go get github.com/gorilla/context
go get github.com/gorilla/sessions
go get github.com/jmoiron/sqlx
go get github.com/go-sql-driver/mysql
go get code.google.com/p/go.tools/cmd/goimports
go get code.google.com/p/go.net/context
go get golang.org/x/oauth2
go get github.com/go-redis/redis
go get github.com/alecthomas/gometalinter
go get github.com/bradfitz/gomemcache/memcache
go get github.com/gregjones/httpcache
go get github.com/bradleypeabody/gorilla-sessions-memcache