go get github.com/gorilla/mux
go get github.com/jmcvetta/napping
go get github.com/pebbe/zmq4
go get github.com/gorilla/context
go get github.com/gorilla/sessions
go get github.com/jmoiron/sqlx
go get github.com/go-sql-driver/mysql
go get github.com/golang/lint/golint
go get code.google.com/p/go.tools/cmd/goimports
go get golang.org/x/tools/cmd/vet
go get code.google.com/p/go.net/context