/* 
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.2.6.dev1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package esi

import (
	"time"
)

// transaction
type GetCharactersCharacterIdWalletsJournal200Ok struct {

	// argument_name string
	ArgumentName string `json:"argument_name,omitempty"`

	// argument_value integer
	ArgumentValue int32 `json:"argument_value,omitempty"`

	// first_party_id integer
	FirstPartyId int32 `json:"first_party_id,omitempty"`

	// first_party_type string
	FirstPartyType string `json:"first_party_type,omitempty"`

	// post_transaction_balance integer
	PostTransactionBalance int64 `json:"post_transaction_balance,omitempty"`

	// reason string
	Reason string `json:"reason,omitempty"`

	// ref_id integer
	RefId int64 `json:"ref_id,omitempty"`

	// ref_type string
	RefType string `json:"ref_type,omitempty"`

	// second_party_id integer
	SecondPartyId int32 `json:"second_party_id,omitempty"`

	// second_party_type string
	SecondPartyType string `json:"second_party_type,omitempty"`

	// tax_amount integer
	TaxAmount int64 `json:"tax_amount,omitempty"`

	// tax_reciever_id integer
	TaxRecieverId int32 `json:"tax_reciever_id,omitempty"`

	// Positive if transferred to first party, negative if transferred to second party
	TransactionAmount int64 `json:"transaction_amount,omitempty"`

	// transaction_date string
	TransactionDate time.Time `json:"transaction_date,omitempty"`
}
