// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/tokenstore/token.proto

/*
Package tokenstore is a generated protocol buffer package.

It is generated from these files:
	internal/tokenstore/token.proto

It has these top-level messages:
	SetResponse
	GetTokenRequest
	SetTokenRequest
	Token
*/
package tokenstore

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetResponse struct {
	Ok bool `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
}

func (m *SetResponse) Reset()                    { *m = SetResponse{} }
func (m *SetResponse) String() string            { return proto.CompactTextString(m) }
func (*SetResponse) ProtoMessage()               {}
func (*SetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SetResponse) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type GetTokenRequest struct {
	CharacterID      int32 `protobuf:"varint,1,opt,name=characterID" json:"characterID,omitempty"`
	TokenCharacterID int32 `protobuf:"varint,2,opt,name=tokenCharacterID" json:"tokenCharacterID,omitempty"`
}

func (m *GetTokenRequest) Reset()                    { *m = GetTokenRequest{} }
func (m *GetTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTokenRequest) ProtoMessage()               {}
func (*GetTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetTokenRequest) GetCharacterID() int32 {
	if m != nil {
		return m.CharacterID
	}
	return 0
}

func (m *GetTokenRequest) GetTokenCharacterID() int32 {
	if m != nil {
		return m.TokenCharacterID
	}
	return 0
}

type SetTokenRequest struct {
	CharacterID      int32                      `protobuf:"varint,1,opt,name=characterID" json:"characterID,omitempty"`
	TokenCharacterID int32                      `protobuf:"varint,2,opt,name=tokenCharacterID" json:"tokenCharacterID,omitempty"`
	TokenType        string                     `protobuf:"bytes,3,opt,name=tokenType" json:"tokenType,omitempty"`
	AccessToken      string                     `protobuf:"bytes,4,opt,name=accessToken" json:"accessToken,omitempty"`
	RefreshToken     string                     `protobuf:"bytes,5,opt,name=refreshToken" json:"refreshToken,omitempty"`
	Expiry           *google_protobuf.Timestamp `protobuf:"bytes,6,opt,name=Expiry" json:"Expiry,omitempty"`
}

func (m *SetTokenRequest) Reset()                    { *m = SetTokenRequest{} }
func (m *SetTokenRequest) String() string            { return proto.CompactTextString(m) }
func (*SetTokenRequest) ProtoMessage()               {}
func (*SetTokenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetTokenRequest) GetCharacterID() int32 {
	if m != nil {
		return m.CharacterID
	}
	return 0
}

func (m *SetTokenRequest) GetTokenCharacterID() int32 {
	if m != nil {
		return m.TokenCharacterID
	}
	return 0
}

func (m *SetTokenRequest) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *SetTokenRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *SetTokenRequest) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *SetTokenRequest) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

type Token struct {
	TokenType    string                     `protobuf:"bytes,1,opt,name=tokenType" json:"tokenType,omitempty"`
	AccessToken  string                     `protobuf:"bytes,2,opt,name=accessToken" json:"accessToken,omitempty"`
	RefreshToken string                     `protobuf:"bytes,3,opt,name=refreshToken" json:"refreshToken,omitempty"`
	Expiry       *google_protobuf.Timestamp `protobuf:"bytes,4,opt,name=Expiry" json:"Expiry,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Token) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Token) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *Token) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *Token) GetExpiry() *google_protobuf.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func init() {
	proto.RegisterType((*SetResponse)(nil), "tokenstore.SetResponse")
	proto.RegisterType((*GetTokenRequest)(nil), "tokenstore.GetTokenRequest")
	proto.RegisterType((*SetTokenRequest)(nil), "tokenstore.SetTokenRequest")
	proto.RegisterType((*Token)(nil), "tokenstore.Token")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TokenStore service

type TokenStoreClient interface {
	// Sends a greeting
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*Token, error)
	SetToken(ctx context.Context, in *SetTokenRequest, opts ...grpc.CallOption) (*SetResponse, error)
}

type tokenStoreClient struct {
	cc *grpc.ClientConn
}

func NewTokenStoreClient(cc *grpc.ClientConn) TokenStoreClient {
	return &tokenStoreClient{cc}
}

func (c *tokenStoreClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := grpc.Invoke(ctx, "/tokenstore.TokenStore/GetToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenStoreClient) SetToken(ctx context.Context, in *SetTokenRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	out := new(SetResponse)
	err := grpc.Invoke(ctx, "/tokenstore.TokenStore/SetToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TokenStore service

type TokenStoreServer interface {
	// Sends a greeting
	GetToken(context.Context, *GetTokenRequest) (*Token, error)
	SetToken(context.Context, *SetTokenRequest) (*SetResponse, error)
}

func RegisterTokenStoreServer(s *grpc.Server, srv TokenStoreServer) {
	s.RegisterService(&_TokenStore_serviceDesc, srv)
}

func _TokenStore_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenstore.TokenStore/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TokenStore_SetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenStoreServer).SetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tokenstore.TokenStore/SetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenStoreServer).SetToken(ctx, req.(*SetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TokenStore_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tokenstore.TokenStore",
	HandlerType: (*TokenStoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _TokenStore_GetToken_Handler,
		},
		{
			MethodName: "SetToken",
			Handler:    _TokenStore_SetToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/tokenstore/token.proto",
}

func init() { proto.RegisterFile("internal/tokenstore/token.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xbd, 0x4e, 0xc3, 0x30,
	0x14, 0x85, 0xeb, 0xf4, 0x47, 0xed, 0x2d, 0xa2, 0xe0, 0x85, 0x28, 0x80, 0x1a, 0x79, 0xaa, 0x18,
	0x5c, 0xa9, 0xac, 0x4c, 0xfc, 0x08, 0xb1, 0x3a, 0xdd, 0x51, 0x1a, 0xdd, 0xfe, 0x28, 0x6d, 0x1c,
	0x6c, 0x57, 0xa2, 0x2f, 0xc1, 0x2b, 0xf0, 0x98, 0xac, 0x28, 0x0e, 0x51, 0xd2, 0x80, 0x28, 0x0b,
	0x5b, 0x74, 0xce, 0xb9, 0xb9, 0x9f, 0xae, 0x0f, 0x0c, 0x57, 0x89, 0x41, 0x95, 0x84, 0xeb, 0xb1,
	0x91, 0x31, 0x26, 0xda, 0x48, 0x85, 0xf9, 0x27, 0x4f, 0x95, 0x34, 0x92, 0x42, 0xa9, 0x7b, 0xc3,
	0x85, 0x94, 0x8b, 0x35, 0x8e, 0xad, 0x33, 0xdb, 0xce, 0xc7, 0x66, 0xb5, 0x41, 0x6d, 0xc2, 0x4d,
	0x9a, 0x87, 0xd9, 0x25, 0xf4, 0x03, 0x34, 0x02, 0x75, 0x2a, 0x13, 0x8d, 0xf4, 0x18, 0x1c, 0x19,
	0xbb, 0xc4, 0x27, 0xa3, 0xae, 0x70, 0x64, 0xcc, 0x9e, 0x61, 0xf0, 0x88, 0x66, 0x9a, 0xfd, 0x50,
	0xe0, 0xcb, 0x16, 0xb5, 0xa1, 0x3e, 0xf4, 0xa3, 0x65, 0xa8, 0xc2, 0xc8, 0xa0, 0x7a, 0xba, 0xb7,
	0xd9, 0xb6, 0xa8, 0x4a, 0xf4, 0x0a, 0x4e, 0x2c, 0xc2, 0x5d, 0x25, 0xe6, 0xd8, 0xd8, 0x37, 0x9d,
	0x7d, 0x10, 0x18, 0x04, 0xff, 0xb9, 0x81, 0x5e, 0x40, 0xcf, 0x6a, 0xd3, 0x5d, 0x8a, 0x6e, 0xd3,
	0x27, 0xa3, 0x9e, 0x28, 0x85, 0x6c, 0x57, 0x18, 0x45, 0xa8, 0xb5, 0x25, 0x70, 0x5b, 0xd6, 0xaf,
	0x4a, 0x94, 0xc1, 0x91, 0xc2, 0xb9, 0x42, 0xbd, 0xcc, 0x23, 0x6d, 0x1b, 0xd9, 0xd3, 0xe8, 0x04,
	0x3a, 0x0f, 0xaf, 0xe9, 0x4a, 0xed, 0xdc, 0x8e, 0x4f, 0x46, 0xfd, 0x89, 0xc7, 0xf3, 0xbb, 0xf3,
	0xe2, 0xee, 0x7c, 0x5a, 0xdc, 0x5d, 0x7c, 0x25, 0xd9, 0x3b, 0x81, 0x76, 0x3e, 0xbd, 0x47, 0x48,
	0x0e, 0x10, 0x3a, 0x87, 0x09, 0x9b, 0xbf, 0x12, 0xb6, 0xfe, 0x4a, 0x38, 0x79, 0x23, 0x00, 0x76,
	0x3a, 0xc8, 0xba, 0x44, 0x6f, 0xa0, 0x5b, 0x74, 0x81, 0x9e, 0xf3, 0xb2, 0x64, 0xbc, 0xd6, 0x10,
	0xef, 0xb4, 0x6a, 0x5a, 0x87, 0x35, 0xe8, 0x2d, 0x74, 0x83, 0x1f, 0xa7, 0x6b, 0xaf, 0xef, 0x9d,
	0xd5, 0xcc, 0xa2, 0x9b, 0xac, 0x31, 0xeb, 0x58, 0xd8, 0xeb, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x9e, 0x6d, 0x37, 0x91, 0x03, 0x03, 0x00, 0x00,
}
