apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: evedata-tailor
  namespace: evedata
spec:
  replicas: 1
  template:
    metadata:
      name: evedata-tailor
      labels:
        app: tailor
      annotations:
        prometheus.io/scrape: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - tailor
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: evedata-tailor
        image: antihax/evedata-tailor
        imagePullPolicy: Always
        env:
        - name: B2_ACCOUNTID
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: b2-accountID
        - name: B2_APPLICATION_KEY
          valueFrom:
            secretKeyRef:
              name: esi-secret
              key: b2-application-key       
        - name: SQLAUTH
          valueFrom:
            secretKeyRef:
              name: sql-password
              key: sqlauth           
        ports:
        - containerPort: 3000
        volumeMounts:
        - mountPath: /etc/ssl/certs
          name: ca-certs
      volumes:
      - name: ca-certs
        hostPath:
          path: /etc/ssl/certs
          type: Directory
